---
- name: Registrar uptime del sistema
  command: uptime
  register: variable_uptime

- name: Generar informe de auditor√≠a desde plantilla
  template:
    src: server_info.j2
    dest: "{{ log_path }}"
